version: "3"
services:
    gen_data:
        build: generate_data/
        command: python ./data_creation.py
    model:
        build: model/
        command: python ./model_preprocessing.py
        command: python ./model_preparation.py
    test:
        build: test/
        command: python ./model_testing.py
